[general]
connection = "Host=127.0.0.1;Port=5432;Database=fsnix;Username=fsnix;Password=fsnix"
output = "Database.Generated.fs"
namespace = "App.Database"
cli_mutable = false

[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true

[filters]
include = [
  "fsnix/current_feature_flag_definitions",
  "fsnix/feature_flag_history"
]
exclude = []
