// This code was generated by `SqlHydra.Npgsql` -- v5.0.0.
namespace App.Database.Schema

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(5, 0, 0)
    let ns = "App.Database.Schema"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module fsnix =

    type current_feature_flag_definitions =
        { [<ProviderDbType("Text")>]
          name: Option<string>
          [<ProviderDbType("Boolean")>]
          enabled: Option<bool>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          valid_to: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          recorded_at: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "name"
                    Value = box this.name
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "enabled"
                    Value = box this.enabled
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "valid_from"
                    Value = box this.valid_from
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "valid_to"
                    Value = box this.valid_to
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = Some "TimestampTz" } ]

    let current_feature_flag_definitions = table<current_feature_flag_definitions>

    type feature_flag_history =
        { [<ProviderDbType("Text")>]
          name: Option<string>
          [<ProviderDbType("Boolean")>]
          enabled: Option<bool>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          valid_to: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          recorded_at: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "name"
                    Value = box this.name
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "enabled"
                    Value = box this.enabled
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "valid_from"
                    Value = box this.valid_from
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "valid_to"
                    Value = box this.valid_to
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = Some "TimestampTz" } ]

    let feature_flag_history = table<feature_flag_history>

    type feature_flag_intervals =
        { [<ProviderDbType("Text")>]
          feature_name: string
          [<ProviderDbType("Boolean")>]
          enabled: bool
          [<ProviderDbType("TimestampTzRange")>]
          valid_during: NpgsqlTypes.NpgsqlRange<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          recorded_at: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "feature_name"
                    Value = box this.feature_name
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "enabled"
                    Value = box this.enabled
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "valid_during"
                    Value = box this.valid_during
                    ProviderDbType = Some "TimestampTzRange" }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = Some "TimestampTz" } ]

    let feature_flag_intervals = table<feature_flag_intervals>

    type feature_flags =
        { [<ProviderDbType("Text")>]
          name: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "name"
                    Value = box this.name
                    ProviderDbType = Some "Text" } ]

    let feature_flags = table<feature_flags>

    type next_feature_flag_boundary =
        { [<ProviderDbType("TimestampTz")>]
          observed_at: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          next_boundary: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "observed_at"
                    Value = box this.observed_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "next_boundary"
                    Value = box this.next_boundary
                    ProviderDbType = Some "TimestampTz" } ]

    let next_feature_flag_boundary = table<next_feature_flag_boundary>

    type user_tokens =
        { [<ProviderDbType("Uuid")>]
          user_id: System.Guid
          [<ProviderDbType("Varchar")>]
          login_provider: string
          [<ProviderDbType("Varchar")>]
          name: string
          [<ProviderDbType("Text")>]
          value: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "user_id"
                    Value = box this.user_id
                    ProviderDbType = Some "Uuid" }
                  { WriteColumn.Name = "login_provider"
                    Value = box this.login_provider
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "name"
                    Value = box this.name
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "value"
                    Value = box this.value
                    ProviderDbType = Some "Text" } ]

    let user_tokens = table<user_tokens>

    type users =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Varchar")>]
          username: string
          [<ProviderDbType("Varchar")>]
          normalized_username: string
          [<ProviderDbType("Varchar")>]
          email: string
          [<ProviderDbType("Varchar")>]
          normalized_email: string
          [<ProviderDbType("Boolean")>]
          email_confirmed: bool
          [<ProviderDbType("Text")>]
          password_hash: Option<string>
          [<ProviderDbType("Boolean")>]
          two_factor_enabled: bool
          [<ProviderDbType("Text")>]
          security_stamp: string
          [<ProviderDbType("Text")>]
          concurrency_stamp: string
          [<ProviderDbType("TimestampTz")>]
          lockout_end: Option<System.DateTime>
          [<ProviderDbType("Boolean")>]
          lockout_enabled: bool
          [<ProviderDbType("Integer")>]
          access_failed_count: int }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "id"
                    Value = box this.id
                    ProviderDbType = Some "Uuid" }
                  { WriteColumn.Name = "username"
                    Value = box this.username
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "normalized_username"
                    Value = box this.normalized_username
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "email"
                    Value = box this.email
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "normalized_email"
                    Value = box this.normalized_email
                    ProviderDbType = Some "Varchar" }
                  { WriteColumn.Name = "email_confirmed"
                    Value = box this.email_confirmed
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "password_hash"
                    Value = box this.password_hash
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "two_factor_enabled"
                    Value = box this.two_factor_enabled
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "security_stamp"
                    Value = box this.security_stamp
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "concurrency_stamp"
                    Value = box this.concurrency_stamp
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "lockout_end"
                    Value = box this.lockout_end
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "lockout_enabled"
                    Value = box this.lockout_enabled
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "access_failed_count"
                    Value = box this.access_failed_count
                    ProviderDbType = Some "Integer" } ]

    let users = table<users>



type QueryContextFactory =
    {
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
        /// Disposes the NpgsqlDataSource when the factory created it from a connection string; a no-op when the caller supplied their own.
        Dispose: unit -> unit
    }

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        // The factory creates this data source, so it owns and disposes it.
        let dataSource = Npgsql.NpgsqlDataSource.Create(connectionString)
        QueryContextFactory.CreateInternal(dataSource, (fun () -> dataSource.Dispose()), ?sqlLogger = sqlLogger)

    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        // The caller supplied this data source, so the caller owns its lifetime.
        QueryContextFactory.CreateInternal(dataSource, ignore, ?sqlLogger = sqlLogger)

    static member private CreateInternal(dataSource: Npgsql.NpgsqlDataSource, dispose: unit -> unit, ?sqlLogger) =
        let emitter = SqlHydra.Query.PostgresEmitter()

        let createConn () : System.Data.Common.DbConnection = dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync
          Dispose = dispose }
