// This code was generated by `SqlHydra.Npgsql` -- v3.4.0.
namespace App.Database

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 4, 0)
    let ns = "App.Database"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module fsnix =

    type current_feature_flag_definitions =
        { [<ProviderDbType("Text")>]
          name: Option<string>
          [<ProviderDbType("Boolean")>]
          enabled: Option<bool>
          [<ProviderDbType("Text")>]
          filter_name: Option<string>
          [<ProviderDbType("Text")>]
          filter_parameters: Option<string>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          valid_to: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          recorded_at: Option<System.DateTime> }

    let current_feature_flag_definitions = table<current_feature_flag_definitions>

    type feature_flag_history =
        { [<ProviderDbType("Text")>]
          name: Option<string>
          [<ProviderDbType("Boolean")>]
          enabled: Option<bool>
          [<ProviderDbType("Text")>]
          filter_name: Option<string>
          [<ProviderDbType("Text")>]
          filter_parameters: Option<string>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          valid_to: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          recorded_at: Option<System.DateTime> }

    let feature_flag_history = table<feature_flag_history>


[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        QueryContextFactory.Create(Npgsql.NpgsqlDataSource.Create(connectionString), ?sqlLogger = sqlLogger)

    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        let compiler = SqlKata.Compilers.PostgresCompiler()

        let createConn () : System.Data.Common.DbConnection = dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
